name: CheckPush-Website
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE
      - .github/*
      - .gitattributes
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: 环境初始化
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: yarn安装
        run: yarn install
        with:
          node-version: '18'
      - name: 验证提交
        uses: actions/checkout@v2
        with:
          node-version: $

      - name: 构建测试
        uses: jenkey2011/vuepress-deploy@master
        with:
          node-version: $
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: HaoduStudio/website
          TARGET_BRANCH: master
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist/
          COMMIT_MESSAGE: Auto Deploy Success
          CNAME: dailynotes.top
